name: hackropole_editeur_de_configuration
source: hackropole
url: https://hackropole.fr/fr/challenges/pwn/fcsc2025-pwn-editeur-de-configuration/
theme: "\n            "
category: pwn
difficulty: medium
description: 'Challenge Éditeur de configuration — '
runtime: file
file:
- editeur-de-configuration
- Dockerfile
flag:
  format: FCSC{...}
  value: 1656fbc3de07fffc4635656753a74b56c9d4ce2525e9d41daa040da2a2e206a6
writeup: writeups/hackropole_editeur_de_configuration.md
enabled: true
